@address = http://localhost:8080
@dataset_path = pipeline1

### Create new branch
POST {{address}}/create_pipeline/ HTTP/1.1
content-type: application/json

{
  "name": "pipeline1",
  "transformation_steps": [
      {"name": "step1", "image": "transformation-step:1"},
      {"name": "step2", "image": "transformation-step:1"}
  ]
}

### Get dataset
GET {{address}}/get_pipelines/ HTTP/1.1