apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: job-wq-1
    spec:
      volumes:
      - name: data-volume
        emptyDir: {}
      containers:
      - name: iterum-sidecar
        image: iterum-sidecar:1
        env:
        - name: BROKER_URL
          value: amqp://iterum:sinaasappel@iterum-mq-rabbitmq-ha:5672
        - name: INPUT_QUEUE
          value: job1_input
        - name: OUTPUT_QUEUE
          value: job1_output
        - name: MINIO_URL
          value: iterum-minio:9000
        - name: MINIO_ACCESS_KEY
          value: iterum
        - name: MINIO_SECRET_KEY
          value: banaanappel
        - name: MINIO_OUTPUT_BUCKET
          value: outputbucket
        - name: DATA_VOLUME_PATH
          value: /data-volume
        volumeMounts:
        - name: data-volume
          mountPath: /data-volume
      - name: transformation-step
        image: transformation-step:1
        env:
        - name: DATA_VOLUME_PATH
          value: /data-volume
        volumeMounts:
        - name: data-volume
          mountPath: /data-volume
      restartPolicy: OnFailure
     