apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: create-iterum-pipeline-job_manager-service-account
 namespace: default
roleRef:
 kind: Role
 name: create-iterum-pipeline-job
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: manager-service-account
  namespace: default
