apiVersion: v1
kind: PersistentVolume
metadata:
  name: daemon-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/snap/microk8s/common/default-storage/daemon-storage"
