apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mark/development/iterum/ego-photos-minio-mount/ego-photos-minio"
