apiVersion: v1
kind: PersistentVolume
metadata:
  name: daemon-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/localStorage/daemon-storage/"
