apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ego-photos-non-iterum-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150G
