apiVersion: v1
kind: PersistentVolume
metadata:
  name:  non-iterum-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 150G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: ego-photos-non-iterum-pv-claim
  gcePersistentDisk:
    pdName: non-iterum-ego-photos-volume
    fsType: ext4
